[package]
edition = "2021"
name    = "monkey_rs"
version = "0.1.0"

[lib]
name = "monkey_rs"
path = "src/lib.rs"

[[bin]]
name = "monkey_rs_repl"
path = "src/bin/repl/main.rs"

[dependencies]
anyhow = "1"
